### ISSUE TITLE
RandomUser v.1.0.0 is missing commons-io-2.8.0.jar

### ISSUE THREAD

**Issue by edwinvanelk** [ar-mendix/RandomUser#2]
RandomUser v.1.0.0 is using org.apache.commons.io.IOUtils.

However, the required library e.g. commons-io-2.8.0.jar is not included in the module. Using a _blank app this gives a java compilation error:

    [javac] Compiling 2 source files to D:\Mendix\RandomUser\deployment\run\bin
    [javac] D:\Mendix\RandomUser\javasource\randomuser\FileHandling.java:14: error: package org.apache.commons.io does not exist
    [javac] import org.apache.commons.io.IOUtils;
    [javac]                             ^
    [javac] D:\Mendix\RandomUser\javasource\randomuser\FileHandling.java:53: error: cannot find symbol

Can you include commons-io-2.8.0.jar in the next release?

P.S. In Github the userlib folder contains a commons-io-2.8.0.jar file, but this userlib folder is not included in v 1.0.0 of the .mpk file.  And might the file commons-io-2.8.0.jar.CommunityCommons.RequiredLib be renamed to something like commons-io-2.8.0.jar.RandomUser.RequiredLib then too?

**Comment by ar-mendix** [comment]
I've submitted an updated version to the marketplace, thank you for the feedback!

**Comment by edwinvanelk** [comment]
Can you add a commons-io-2.8.0.jar.RandomUser.RequiredLib file too in the userlib folder? To be able to determine for which module(s) a library is needed/used.

**Comment by ar-mendix** [comment]
I've submitted another copy with that file added to the lib folder. At least I think I've done it right.
